/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if _MSC_VER
#pragma pack (push,4)
#endif

#ifndef WOT_API
#define WOT_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern WOT_API FName WOT_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY

enum ELoadSave
{
    LS_Load                 =0,
    LS_Save                 =1,
    LS_MAX                  =2,
};
enum ETransitionType
{
    TRT_None                =0,
    TRT_EndOfLevel          =1,
    TRT_RestartLevel        =2,
    TRT_LoadLevel           =3,
    TRT_NewGame             =4,
    TRT_MAX                 =5,
};
enum EMotionDirection
{
    MD_None                 =0,
    MD_Forward              =1,
    MD_Backward             =2,
    MD_Left                 =3,
    MD_Right                =4,
    MD_MAX                  =5,
};
#define UCONST_MaxNPCTypes 32
#define UCONST_NPCStats_PerNPCX 0x04
#define UCONST_NPCStats_PerNPC 0x02
#define UCONST_NPCStats_Totals 0x01
#define UCONST_ThisClassName WotPlayer
#define UCONST_WalkAnimSlot Walk
#define UCONST_SwimAnimSlot Swim
#define UCONST_RunRAnimSlot RunR
#define UCONST_RunLAnimSlot RunL
#define UCONST_RunAnimSlot Run
#define UCONST_LookAnimSlot Look
#define UCONST_LandAnimSlot Land
#define UCONST_JumpAnimSlot Jump
#define UCONST_HitHardAnimSlot HitHard
#define UCONST_HitAnimSlot Hit
#define UCONST_FallAnimSlot Fall
#define UCONST_DeathAnimSlot Death
#define UCONST_BreathAnimSlot Breath
#define UCONST_AttackWalkAnimSlot AttackWalk
#define UCONST_AttackRunRAnimSlot AttackRunR
#define UCONST_AttackRunLAnimSlot AttackRunL
#define UCONST_AttackRunAnimSlot AttackRun
#define UCONST_AttackAnimSlot Attack
#define UCONST_CE_PORTCULLIS 9
#define UCONST_CE_STAIRCASE 8
#define UCONST_CE_PIT 7
#define UCONST_CE_WALL 6
#define UCONST_CE_FIREWALL 5
#define UCONST_CE_SPEAR 4
#define UCONST_CE_ALARM 3
#define UCONST_CE_CAPTAIN 2
#define UCONST_CE_GRUNT 1
#define UCONST_CE_SEALS 0
#define UCONST_TELEPORT_FAIL_MESSAGE_DELAY 4.0
#define UCONST_TRACE_DISTANCE 3200
#define UCONST_MAX_ZONE 63

class WOT_API AWOTPlayer : public APlayerPawn
{
public:
    BYTE TransitionType;
    class AIconInfo* FirstIcon;
    INT SeekerCount;
    class AHandSet* AngrealHandSet;
    class AHandSet* CitadelEditorHandSet;
    class AHandSet* CurrentHandSet;
    class AHUD* PrevHUD;
    BITFIELD bPrevShowMenu:1 GCC_PACK(4);
    BITFIELD bSkipPaintProgress:1;
    BITFIELD bSkipProgressFog:1;
    class ABudgetInfo* Budget GCC_PACK(4);
    BITFIELD bEditing:1 GCC_PACK(4);
    BITFIELD bTeleportingDisabled:1;
    FLOAT LastTeleportFailMessage GCC_PACK(4);
    FVector EditStartLoc;
    FRotator EditStartRot;
    INT SelectedZone;
    FRotator ViewOffset;
    BITFIELD bShowOverview:1 GCC_PACK(4);
    class AScoreBoard* Overview GCC_PACK(4);
    class UClass* OverviewType;
    FName NextAnim;
    FLOAT MinDamageToShake;
    FLOAT RespawnDelaySecs;
    FLOAT OKToFireTime;
    INT SkinSwitchLevel;
    FStringNoInit AltSkinStr;
    BITFIELD bTeleFragPawns:1 GCC_PACK(4);
    FLOAT RestartLevelDelaySecs GCC_PACK(4);
    BITFIELD bShowHitActors:1 GCC_PACK(4);
    BITFIELD bSpamHitActors:1;
    BITFIELD bShowHiddenClasses:1;
    FName NPCNames[16] GCC_PACK(4);
    BITFIELD bForceRotation:1 GCC_PACK(4);
    FRotator ForcedRotationRate GCC_PACK(4);
    BYTE MotionDirection;
    FLOAT NextTauntTime;
    FLOAT MinTimeBetweenTaunts;
    class UClass* TextureHelperClass;
    class UClass* DamageHelperClass;
    class AGenericAssetsHelper* AssetsHelper;
    class UClass* SoundTableClass;
    class ASoundTableWOT* MySoundTable;
    class UClass* SoundSlotTimerListClass;
    class ASoundSlotTimerListInterf* MySoundSlotTimerList;
    FLOAT VolumeMultiplier;
    FLOAT RadiusMultiplier;
    FLOAT PitchMultiplier;
    FLOAT TimeBetweenHitSoundsMin;
    FLOAT TimeBetweenHitSoundsMax;
    class UClass* AnimationTableClass;
    BITFIELD bTestAnimTable:1 GCC_PACK(4);
    FLOAT NextPainSoundTime GCC_PACK(4);
    FLOAT HitHardHealthRatio;
    FLOAT ExceptionalDeathHealthRatio;
    FLOAT WalkBackwardSpeedMultiplier;
    BITFIELD bSetSpeedCheatOn:1 GCC_PACK(4);
    FLOAT SpeedPlayAnimAfterLanding GCC_PACK(4);
    FLOAT PlayLandHardMinVelocity;
    FLOAT PlayLandSoftMinVelocity;
    FLOAT LadderLandingNoiseVelocity;
    FLOAT LadderLandedHitNormalZ;
    FLOAT GibForSureFinalHealth;
    FLOAT GibSometimesFinalHealth;
    FLOAT GibSometimesOdds;
    FLOAT BaseGibDamage;
    BITFIELD bNeverGib:1 GCC_PACK(4);
    BITFIELD bCarcassSpawned:1;
    class UClass* DefaultAngrealInventory GCC_PACK(4);
    FStringNoInit ArtifactNames[55];
    FStringNoInit SelectedStr;
    FStringNoInit TerAngrealStr;
    FStringNoInit InventoryInfoHitStr;
    FName SubTitlesPackageName;
    BITFIELD bSubtitles:1 GCC_PACK(4);
    FStringNoInit SubTitleLanguages[5] GCC_PACK(4);
    FLOAT MessageDurationSecsPerChar;
    FLOAT MinMessageDuration;
    BITFIELD bShowSounds:1 GCC_PACK(4);
    BITFIELD bShowOtherSounds:1;
    BITFIELD bShowLocalizeSoundErrors:1;
    FLOAT InventoryInfoHintDuration GCC_PACK(4);
    class AWOTHelpInfo* WOTHelpItem;
    FName AngrealHandOrder[100];
    FName IllusionAnimSequence;
    FLOAT IllusionAnimRate;
    FLOAT PlayerRestartGameDelay;
    FVector SAOffset;
    class UClass* DefaultReflectorClasses[20];
    class AReflector* CurrentReflector;
    class ALeech* FirstLeech;
    class UClass* ApparentClass;
    INT ApparentTeam;
    class UTexture* ApparentIcon;
    class UTexture* HealthIcons[4];
    class UTexture* DisguiseIcon;
    INT NumDeaths;
    FName PlayerColor;
    INT ShieldHitPoints;
    class APawn* SuicideInstigator;
    FLOAT SuicideInstigationTime;
    BITFIELD bAcceptedInventory:1 GCC_PACK(4);
    class UClass* PlayerClass GCC_PACK(4);
    FPlayerTroopMap PlayerTroops[12];
    FStringNoInit TeamDescription;
    INT JoinTeamTimeout;
    BITFIELD bProhibitEditorExit:1 GCC_PACK(4);
    FStringNoInit CantChangeTeamsStr GCC_PACK(4);
    FStringNoInit TeleportProhibitedEditingStr;
    FStringNoInit TeleportProhibitedJoinStr;
    FStringNoInit WaitingForSealsStr;
    FStringNoInit WaitingForEditStr;
    FStringNoInit CantEditLevelStr;
    FStringNoInit CantEditZoneStr;
    FStringNoInit CantEditAreaStr;
    FStringNoInit CantEditNowStr;
    FStringNoInit CantEditBudgetStr;
    FStringNoInit CantEditLimitStr;
    FStringNoInit CantPlaceResourceStr;
    FStringNoInit CantLeaveEditorStr;
    DECLARE_FUNCTION(execTraceVisible);
    DECLARE_FUNCTION(execGetLocationZoneInfo);
    DECLARE_FUNCTION(execGetZoneInfo);
    DECLARE_CLASS(AWOTPlayer,APlayerPawn,0|CLASS_Config)
    NO_DEFAULT_CONSTRUCTOR(AWOTPlayer)
};

#define UCONST_WalkAnimSlot Walk
#define UCONST_WaitAnimSlot Wait
#define UCONST_SwimAnimSlot Swim
#define UCONST_RunAnimSlot Run
#define UCONST_LookAnimSlot Look
#define UCONST_LandAnimSlot Land
#define UCONST_JumpAnimSlot Jump
#define UCONST_HitHardAnimSlot HitHard
#define UCONST_HitAnimSlot Hit
#define UCONST_FallAnimSlot Fall
#define UCONST_DeathAnimSlot Death
#define UCONST_BreathAnimSlot Breath
#define UCONST_TeamAny 252
#define UCONST_TeamNone 253
#define UCONST_TeamPC 254
#define UCONST_TeamNPC 255

class WOT_API AWOTPawn : public ALegendPawn
{
public:
    class UClass* DefaultReflectorClasses[20];
    class AReflector* CurrentReflector;
    class ALeech* FirstLeech;
    INT ShieldHitPoints;
    class APawn* SuicideInstigator;
    FLOAT SuicideInstigationTime;
    FName NextAnimSlot;
    class UTexture* DisguiseIcon;
    BYTE AssignedTeam;
    FLOAT MinTimeBetweenWeaponSwitch;
    FLOAT LastWeaponSwitchTime;
    FLOAT GroundSpeedMin;
    FLOAT GroundSpeedMax;
    FLOAT HealthMPMin;
    FLOAT HealthMPMax;
    FLOAT HealthSPMin;
    FLOAT HealthSPMax;
    FLOAT ChanceOfHitAnim;
    class UClass* TextureHelperClass;
    class UClass* DamageHelperClass;
    class AGenericAssetsHelper* AssetsHelper;
    class UClass* SoundTableClass;
    class ASoundTableWOT* MySoundTable;
    class UClass* SoundSlotTimerListClass;
    class ASoundSlotTimerListInterf* MySoundSlotTimerList;
    FLOAT VolumeMultiplier;
    FLOAT RadiusMultiplier;
    FLOAT PitchMultiplier;
    FLOAT TimeBetweenHitSoundsMin;
    FLOAT TimeBetweenHitSoundsMax;
    class UClass* AnimationTableClass;
    BITFIELD bTestAnimTable:1 GCC_PACK(4);
    FLOAT NextPainSoundTime GCC_PACK(4);
    class UClass* CarcassType;
    FLOAT HitHardHealthRatio;
    FLOAT HitSoftHealthRatio;
    FLOAT ExceptionalDeathHealthRatio;
    FLOAT DestroyDelaySecs;
    FLOAT SpeedPlayAnimAfterLanding;
    FLOAT MinLandedDamageVelocity;
    FLOAT FatalLandedDamageVelocity;
    FLOAT PlayLandHardMinVelocity;
    FLOAT PlayLandSoftMinVelocity;
    FLOAT GibForSureFinalHealth;
    FLOAT GibSometimesFinalHealth;
    FLOAT GibSometimesOdds;
    FLOAT BaseGibDamage;
    BITFIELD bNeverGib:1 GCC_PACK(4);
    BITFIELD bCarcassSpawned:1;
    FLOAT SpawnSeparation GCC_PACK(4);
    BITFIELD bEditing:1 GCC_PACK(4);
    DECLARE_CLASS(AWOTPawn,ALegendPawn,0|CLASS_Config)
    NO_DEFAULT_CONSTRUCTOR(AWOTPawn)
};


class WOT_API AWOTZoneInfo : public AZoneInfo
{
public:
    BYTE Team;
    BYTE MinEditDistance;
    FRotator EditViewAngle;
    FLOAT EditViewDistance;
    BITFIELD bAllowEditing:1 GCC_PACK(4);
    BITFIELD bPitZone:1;
    BITFIELD bHealZone:1;
    INT HealPerSec GCC_PACK(4);
    class USound* HealSound;
    BITFIELD bFOVZone:1 GCC_PACK(4);
    FLOAT ZoneFOV GCC_PACK(4);
    BITFIELD bTrigWaterZone:1 GCC_PACK(4);
    FName ReferenceZone GCC_PACK(4);
    BITFIELD bTrigZoneVelocity:1 GCC_PACK(4);
    BITFIELD bUseSteps:1;
    INT NumSteps GCC_PACK(4);
    FLOAT PauseBetweenSteps;
    FVector StepVelocity;
    FVector NewZoneVelocity;
    FLOAT Duration;
    BITFIELD bTrigPainZone:1 GCC_PACK(4);
    FVector SaveViewFog GCC_PACK(4);
    FVector SaveZoneVelocity;
    BITFIELD bZoneVelocityOn:1 GCC_PACK(4);
    class AActor* LastTriggerer GCC_PACK(4);
    INT VZCurrentStep;
    FName PrevStateName;
    BITFIELD bLeechZone:1 GCC_PACK(4);
    class UClass* LeechClasses[16] GCC_PACK(4);
    INT X;
    BITFIELD bTrigZoneVelo2:1 GCC_PACK(4);
    BITFIELD bTrigZoneVelo2InitiallyOn:1;
    FVector MaxZoneVelocity2 GCC_PACK(4);
    FVector MinZoneVelocity2;
    FLOAT TransitionTime2;
    FVector VeloPerSec2;
    BITFIELD bTrigZoneVeloOn:1 GCC_PACK(4);
    FLOAT TriggerDuration GCC_PACK(4);
    FLOAT TimerLeechDuration[3];
    class UTexture* TimerLeechIcon;
    BITFIELD bPersistentTimer:1 GCC_PACK(4);
    BITFIELD bRemoveTimerOnExit:1;
    BITFIELD bTimerOnRight:1;
    BITFIELD bOnlyTimeOnce:1;
    BITFIELD bAttachedTimer:1;
    DECLARE_CLASS(AWOTZoneInfo,AZoneInfo,0)
    NO_DEFAULT_CONSTRUCTOR(AWOTZoneInfo)
};


class WOT_API AWaysZone : public AWOTZoneInfo
{
public:
    FLOAT Visibility;
    BYTE WaysBrightness;
    BYTE WaysSaturation;
    BYTE WaysHue;
    BYTE WaysRadius;
    DECLARE_CLASS(AWaysZone,AWOTZoneInfo,0)
    NO_DEFAULT_CONSTRUCTOR(AWaysZone)
};

#define UCONST_GAME_VERSION 310
#define UCONST_ENGINE_VERSION 333

class WOT_API UVersion : public UObject
{
public:
    DECLARE_CLASS(UVersion,UObject,0)
    NO_DEFAULT_CONSTRUCTOR(UVersion)
};

#endif

AUTOGENERATE_FUNCTION(AWOTPlayer,-1,execTraceVisible);
AUTOGENERATE_FUNCTION(AWOTPlayer,-1,execGetLocationZoneInfo);
AUTOGENERATE_FUNCTION(AWOTPlayer,-1,execGetZoneInfo);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif NAMES_ONLY

#if _MSC_VER
#pragma pack (pop)
#endif
